# Generated by Django 5.2.11 on 2026-03-12 11:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#64748b", max_length=20)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="navis/logos/"),
                ),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="tank",
            name="issue",
            field=models.CharField(
                choices=[
                    ("empty", "Low Volume"),
                    ("parameter", "Unsafe Parameter"),
                    ("pump", "Pump"),
                    ("comms", "Undetectable"),
                    ("ok", "Ok!"),
                ],
                default="ok",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("deployed", "Deployed"),
                    ("problem", "Problem"),
                    ("unresponsive", "Unresponsive"),
                    ("maintenance", "Maintenance"),
                ],
                default="active",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tank",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identifier", models.CharField(max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("spreading_factor", models.IntegerField(default=9)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("radius", models.PositiveIntegerField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gateways",
                        to="navis.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
