# Generated by Django 5.2.11 on 2026-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navis", "0002_entity_tank_issue_alter_node_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="parish",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
