# Generated by Django 5.2.11 on 2026-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_node_parish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tank",
            name="location",
        ),
    ]
