# Generated by Django 5.2.11 on 2026-03-13 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_tank_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="tank",
            name="last_contacted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
